services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.bwutil.entrypoints: "web"
      traefik.http.routers.bwutil.rule: "Host(`bwutil.localtest.me`)"
      traefik.http.services.bwutil.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: bwutil
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: bwutil.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
