services:
  tcp-echo-server:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.tcp-echo-server.entrypoints: "tcp"
      traefik.tcp.routers.tcp-echo-server.rule: "HostSNI(`*`)"
      traefik.tcp.services.tcp-echo-server.loadbalancer.server.port: "9000"
    image: nicolaka/netshoot
    networks:
      - default
      - proxy
  
  # gateway:
  #   healthcheck:
  #     disable: true
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.bwutil.entrypoints: "web"
  #     traefik.http.routers.bwutil.rule: "Host(`bwutil.localtest.me`)"
  #     traefik.http.services.bwutil.loadbalancer.server.port: "8088"
  #   environment:
  #     GATEWAY_SYSTEM_NAME: bwutil
  #     GATEWAY_PUBLIC_HTTP_PORT: 80
  #     GATEWAY_PUBLIC_HTTPS_PORT: 443
  #     GATEWAY_PUBLIC_ADDRESS: bwutil.localtest.me
  #   networks:
  #     - default
  #     - proxy
  # pgadmin:
  #   healthcheck:
  #     disable: false
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.pgadmin.entrypoints: "web"
  #     traefik.http.routers.pgadmin.rule: "Host(`pgadmin.localtest.me`)"
  #     traefik.http.services.pgadmin.loadbalancer.server.port: "8080"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   networks:
  #     - default
  #     - proxy
  #   tty: true
  # postgres:
  #   healthcheck:
  #     disable: true
  #   labels:
  #     traefik.enable: "true"
  #     traefik.tcp.routers.postgres.entrypoints: "postgres"
  #     traefik.tcp.routers.postgres.rule: "HostSNI(`*`)"
  #     traefik.tcp.services.postgres.loadbalancer.server.port: "5432"
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     POSTGRES_DB: "postgres"
  #   networks:
  #     - default
  #     - proxy
  # mysql:
  #   healthcheck:
  #     disable: true
  #   labels:
  #     traefik.enable: "true"
  #     traefik.tcp.routers.mysql.entrypoints: "mysql"
  #     traefik.tcp.routers.mysql.rule: "HostSNI(`*`)"
  #     traefik.tcp.services.mysql.loadbalancer.server.port: "3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "mysql"
  #     MYSQL_DATABASE: "mysql"
  #     MYSQL_USER: "mysql"
  #     MYSQL_PASSWORD: "mysql"
  #   networks:
  #     - default
  #     - proxy
networks:
  default:
  proxy:
    external: true
    name: proxy
